name: CICDpipeline

on:
  push:
    branches:
      - master

jobs:
  first_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 #for cloning the repository

      - uses: actions/setup-node@v3 #to setup node,also the syntax "setup-node" is common you just have to change node to whatever you want to setup
        with:
          node-version: "16" # Installing appropriate node version

      - name: npm install # npm(node package manager) is used to install node dependencies for the project
        run: npm install

      - name: lint #ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code
        run: npm run eslint

      - name: test #running tests
        run: npm test
        
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:3000



